app:
  name: "go-kafka"
  # values: localhost, staging, production
  env: "localhost"
  version: "1.0.0"

http:
  port: "8000"
  cors: true

logger:
  logLevel: "debug"
  rollbarEnv: "go-kafka"

postgres:
  poolMax: 2
  url: "postgres://user:pass@localhost:5432/postgres"

kafka:
  brokers: ["localhost:9092", "localhost:9093"]
  groupID: go-kafka
  initTopics: true

kafkaTopics:
  eventCreated:
    topicName: task_created
    partitions: 10
    replicationFactor: 1

kafkaPublisherConfig:
  topic: event_created
  topicPrefix: eventStore
  partitions: 10
  replicationFactor: 1
