basePath: /v1
definitions:
  v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Using a service as an example
  title: Go Kafka API
  version: "1.0"
paths:
  /tasks:
    delete:
      consumes:
      - application/json
      description: Delete task
      operationId: task
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Delete task
      tags:
      - delete_task
    post:
      consumes:
      - application/json
      description: Update task
      operationId: task
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Update task
      tags:
      - update_task
swagger: "2.0"
